package de.uni_hildesheim.sse.kernel_haven.typechef.util;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import de.uni_hildesheim.sse.kernel_haven.util.Logger;

/**
 * Class for reading extra compiler parameters extracted from Kbuild.
 * It parses kbuildparam.sh, generated by KbuildMiner.
 * 
 * @author Adam
 */
public class KbuildParamFile {
    
    private Map<File, List<String>> parameters;

    private File sourceDir;
    
    /**
     * Creates a new {@link KbuildParamFile} by parsing the given kbuildparam.sh file. This is usually
     * generated by KbuildMiner.
     * 
     * @param file The file to parse.
     * @param sourceDir The source tree directory. Used for resolving $srcPath.
     * 
     * @throws IOException If reading the kbuildparam.sh file fails.
     */
    public KbuildParamFile(File file, File sourceDir) throws IOException {
        parameters = new HashMap<>();
        this.sourceDir = sourceDir;
        readFile(file);
    }
    
    /**
     * Returns the list of extra parameters found for the given file inside the source tree.
     * 
     * @param file The file to get the extra compiler parameters from. Relative to sourceDir.
     * 
     * @return A list of extra compiler parameters; never null; may be empty.
     */
    public List<String> getExtraParameters(File file) {
        List<String> result = new ArrayList<>();
        
        for (Map.Entry<File, List<String>> entry : parameters.entrySet()) {
            if (file.getPath().startsWith(entry.getKey().getPath())) {
                result.addAll(entry.getValue());
            }
        }
        
        for (int i = 0; i < result.size(); i++) {
            String param = result.get(i);
            if (param.indexOf('$') != -1) {
                if (sourceDir != null) {
                    param = param.replace("$srcPath", sourceDir.getPath().toString());
                } else if (param.contains("$srcPath")) {
                    Logger.get().logError("sourceDir not specified; can't resolve $srcPath");
                }
                
                if (param.indexOf('$') != -1) {
                    Logger.get().logWarning("Unkown variable in KbuildParamFile:", param);
                }
                result.set(i, param);
            }
        }
        
        return result;
    }
    
    /**
     * Reads the given kbuildparam.sh file.
     * 
     * @param file The file to read.
     * 
     * @throws IOException If reading the file fails.
     */
    private void readFile(File file) throws IOException {
        BufferedReader in = new BufferedReader(new FileReader(file));
        
        String line;
        while ((line = in.readLine()) != null) {
            parseLine(line);
        }
        
        in.close();
    }
    
    /**
     * Parses a single line of a kbuildparam.sh file.
     * 
     * @param line The line to parse.
     */
    private void parseLine(String line) {
        int colonIndex = line.indexOf(':');
        if (colonIndex <= 0) {
            Logger.get().logError("Invalid line in KbuildParamFile:", line);
            return;
        }
        
        File path = new File(line.substring(0, colonIndex));
        
        if (line.charAt(colonIndex + 1) == ' ') {
            colonIndex++;
        }
        line = line.substring(colonIndex + 1);
        
        List<String> params = parseParams(line);
        if (!parameters.containsKey(path)) {
            parameters.put(path, params);
        } else {
            parameters.get(path).addAll(params);
        }
    }
    
    /**
     * Parses the list of compiler parameters in a line of a kbuildparam.sh file.
     * 
     * @param line The list of parameters to parse.
     * 
     * @return The list of parameters. Never null. May be empty.
     */
    private List<String> parseParams(String line) {
        List<String> result = new ArrayList<>();
        
        StringBuilder current = new StringBuilder();
        
        boolean inSingleQuote = false;
        boolean inDoubleQuote = false;
        
        for (int i = 0; i < line.length(); i++) {
            if (line.charAt(i) == '\\') {
                i++;
                current.append(line.charAt(i));
                continue;
            }
            
            if (!inSingleQuote && !inDoubleQuote && Character.isWhitespace(line.charAt(i))) {
                if (!current.toString().trim().isEmpty()) {
                    result.add(current.toString());
                }
                current = new StringBuilder();
                
            } else if (line.charAt(i) == '\'') {
                inSingleQuote = !inSingleQuote;
                
            } else if (!inSingleQuote && line.charAt(i) == '"') {
                inDoubleQuote = !inDoubleQuote;
                
            } else {
                current.append(line.charAt(i));
            }
        }
        
        if (!current.toString().trim().isEmpty()) {
            result.add(current.toString());
        }
        
        return result;
    }
    
}
